site_name: Airowire Observability & FinOps Docs

theme:
  name: material
  logo: images/airowire-logo.png
  favicon: images/airowire-logo.png
  features:
    - content.code.copy
    - content.code.select
    - navigation.top
    - navigation.expand
    - navigation.sections
    - search.suggest
    - search.highlight
    - header.sticky
    - toc.follow
    - toc.sidebar

plugins:
  - search:
      lang: en
  - pdf-export:
      verbose: true
      combined: false
      enabled_if_env: ENABLE_PDF_EXPORT

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - toc:
      permalink: true
      toc_depth: 4

extra_javascript:
  - javascripts/page-pdf-download.js

nav:
  - Azure:
      - Azure Logs Enablement: azure/logs/logs.md
      - Azure APM Enablement: azure/apm/apm.md
      - Azure DSM on AKS with RabbitMQ: azure/dsm/dsm-solution.md
      - Azure DSM on HA Vms with RabbitMQ: azure/dsm/dsm-ansible.md
      - Azure Cost Optimization: azure/cost-management/cost.md
      - AKS SLA Monitoring: azur/sla/sla.md 
      - DB Monitoring: []

  - AWS:
      - Logs: []
      - APM: []
      - Tracing: []
      - Cost Management: aws/cost-management/aws-ccm.md
      - DB Monitoring: []

  - GCP:
      - Logs: []
      - APM: []
      - Metrics: []
      - Cost Management: []
      - DB Monitoring: []

  - Kubernetes: []
  - FinOps: []
  - Observability:
      - DB Monitoring: []
  - SRE Practices:
      - DB Runbooks: []

